#!/bin/bash

#python run.py --config Data/pf_config.txt --feed Data/test_feed2.txt --map-data Data/map.txt --map-image Data/3ne.gif
python run.py --map-data Data/map.txt --feed Data/test_feed3.txt --map-image Data/3ne.gif --make-feed
